Login front end completed for now
TheRealJackiBoi/BlogExamProject pull request #11
Opened 2023-12-14 14:25 UTC by artiecodes

prettier plugin for tailwindcss probably won't cause any issues?

2023-12-14 23:29 UTC, TheRealJackiBoi requested changes

2023-12-14 23:29 UTC, TheRealJackiBoi commented on src/App.jsx
> -        Hello world!
No no my guy
Det skal være <Outlet /> men bare fjern dine ændringer i app, så kigger jeg på det App.jsx

2023-12-15 08:03 UTC, artiecodes commented
reverted app.jsx

2023-12-16 20:04 UTC, TheRealJackiBoi approved these changes

2023-12-16 20:04 UTC, merged